name: build Gmeek

on:
  workflow_dispatch:
  issues:
    types: [opened, edited, milestoned, deleted, labeled, unlabeled]
  issue_comment:
    types: [created, edited, deleted]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.ref }}
  cancel-in-progress: true

jobs:
  blog:
    runs-on: ubuntu-latest
    steps:
      - uses: Meekdai/workflows/Gmeek@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

